version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: warren-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=warren
      - POSTGRES_DB=warren
    volumes:
    - postgres:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: warren-backend
    volumes:
      - .:/app
    ports:
    - 4000:4000
    - 8181:8181
    env_file:
      - .env
    links:
      - postgres
    depends_on:
      - postgres
    command: >
      /bin/sh -c "npx prisma migrate dev --preview-feature &&
      prisma db seed --preview-feature &&
      yarn run dev"

volumes:
  postgres:
