const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json';
const endpointsFiles = ['./src/server.ts'];

const doc = {
  info: {
    version: '1.0.0',
    title: 'Warren',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:4000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'User',
      description: 'Test',
    },
  ],
  definitions: {
    User: {
      name: 'Jhon Doe',
      age: 29,
      parents: {
        father: 'Simon Doe',
        mother: 'Marie Doe',
      },
      diplomas: [
        {
          school: 'XYZ University',
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: 'XYZ Company',
          },
        },
      ],
    },
    AddUser: {
      $name: 'Jhon Doe',
      $age: 29,
      about: '',
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./src/server.ts');
});
