-- CreateTable
CREATE TABLE "Fundo" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "dt_cancel" TIMESTAMP(3) NOT NULL,
    "admin" TEXT NOT NULL,
    "cd_cvm" TEXT NOT NULL,
    "dt_fim_exerc" TIMESTAMP(3) NOT NULL,
    "classe" TEXT NOT NULL,
    "dt_ini_ativ" TIMESTAMP(3) NOT NULL,
    "cnpj_admin" TEXT NOT NULL,
    "dt_ini_classe" TIMESTAMP(3) NOT NULL,
    "cnpj_fundo" TEXT NOT NULL,
    "dt_ini_exerc" TIMESTAMP(3) NOT NULL,
    "condom" TEXT NOT NULL,
    "dt_ini_sit" TIMESTAMP(3) NOT NULL,
    "cpf_cnpj_gestor" TEXT NOT NULL,
    "sit" TEXT NOT NULL,
    "rentab_fundo" TEXT NOT NULL,
    "pf_pj_gestor" TEXT NOT NULL,
    "invest_qualif" TEXT NOT NULL,
    "vl_patrim_liq" TEXT NOT NULL,
    "gestor" TEXT NOT NULL,
    "trib_lprazo" TEXT NOT NULL,
    "fundo_exclusivo" TEXT NOT NULL,
    "tp_fundo" TEXT NOT NULL,
    "fundo_cotas" TEXT NOT NULL,
    "taxa_perfm" TEXT NOT NULL,
    "dt_patrim_liq" TIMESTAMP(3) NOT NULL,
    "taxa_adm" TEXT NOT NULL,

    PRIMARY KEY ("id")
);
