import prisma from '../database/prisma';
import { IFunds } from './interface';

const addFundInfo = (file: IFunds): void => {
  const funds = Object.entries(file);

  funds.forEach((line) => {
    const {
      ADMIN,
      AUDITOR,
      CD_CVM,
      CLASSE,
      CNPJ_ADMIN,
      CNPJ_AUDITOR,
      CONDOM,
      CPF_CNPJ_GESTOR,
      DENOM_SOCIAL,
      DT_CANCEL,
      DT_CONST,
      DT_FIM_EXERC,
      DT_INI_ATIV,
      DT_INI_CLASSE,
      DT_INI_EXERC,
      DT_INI_SIT,
      DT_PATRIM_LIQ,
      FUNDO_COTAS,
      FUNDO_EXCLUSIVO,
      GESTOR,
      INVEST_QUALIF,
      PF_PJ_GESTOR,
      RENTAB_FUNDO,
      SIT,
      TAXA_ADM,
      TAXA_PERFM,
      TP_FUNDO,
      TRIB_LPRAZO,
      VL_PATRIM_LIQ,
    } = line[1];

    prisma.fundo.upsert({
      create: {
        cnpj_fundo: line[0],
        dt_cancel: DT_CANCEL,
        admin: ADMIN,
        cd_cvm: CD_CVM,
        dt_fim_exerc: DT_FIM_EXERC,
        classe: CLASSE,
        dt_ini_ativ: DT_INI_ATIV,
        cnpj_admin: CNPJ_ADMIN,
        dt_ini_classe: DT_INI_CLASSE,
        dt_ini_exerc: DT_INI_EXERC,
        condom: CONDOM,
        dt_ini_sit: DT_INI_SIT,
        cpf_cnpj_gestor: CPF_CNPJ_GESTOR,
        sit: SIT,
        rentab_fundo: RENTAB_FUNDO,
        pf_pj_gestor: PF_PJ_GESTOR,
        invest_qualif: INVEST_QUALIF,
        vl_patrim_liq: String(VL_PATRIM_LIQ),
        gestor: GESTOR,
        trib_lprazo: TRIB_LPRAZO,
        fundo_exclusivo: FUNDO_EXCLUSIVO,
        tp_fundo: TP_FUNDO,
        fundo_cotas: FUNDO_COTAS,
        taxa_perfm: String(TAXA_PERFM),
        dt_patrim_liq: DT_PATRIM_LIQ,
        taxa_adm: String(TAXA_ADM),
        auditor: AUDITOR,
        denom_social: DENOM_SOCIAL,
        cnpj_auditor: CNPJ_AUDITOR,
        dt_const: DT_CONST,
      },
      update: {
        dt_cancel: DT_CANCEL,
        admin: ADMIN,
        cd_cvm: CD_CVM,
        dt_fim_exerc: DT_FIM_EXERC,
        classe: CLASSE,
        dt_ini_ativ: DT_INI_ATIV,
        cnpj_admin: CNPJ_ADMIN,
        dt_ini_classe: DT_INI_CLASSE,
        dt_ini_exerc: DT_INI_EXERC,
        condom: CONDOM,
        dt_ini_sit: DT_INI_SIT,
        cpf_cnpj_gestor: CPF_CNPJ_GESTOR,
        sit: SIT,
        rentab_fundo: RENTAB_FUNDO,
        pf_pj_gestor: PF_PJ_GESTOR,
        invest_qualif: INVEST_QUALIF,
        vl_patrim_liq: String(VL_PATRIM_LIQ),
        gestor: GESTOR,
        trib_lprazo: TRIB_LPRAZO,
        fundo_exclusivo: FUNDO_EXCLUSIVO,
        tp_fundo: TP_FUNDO,
        fundo_cotas: FUNDO_COTAS,
        taxa_perfm: String(TAXA_PERFM),
        dt_patrim_liq: DT_PATRIM_LIQ,
        taxa_adm: String(TAXA_ADM),
        auditor: AUDITOR,
        denom_social: DENOM_SOCIAL,
        cnpj_auditor: CNPJ_AUDITOR,
        dt_const: DT_CONST,
      },
      where: {
        cnpj_fundo: line[0],
      },
    });
  });
};

export default addFundInfo;
